### ISSUE TITLE
Little push to get up and running

### ISSUE THREAD

**Issue by JLKM** [GiraffeKey/griffin#4]
I have managed to get this far:
```

Jan@JLKM1 MINGW64 /f/mockups/gundb/griffinnode
$ npm install
npm WARN gun@0.2020.520 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN gun@0.2020.520 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN griffin-nodejs@0.1.17 No description
npm WARN griffin-nodejs@0.1.17 No repository field.

removed 1 package and audited 402 packages in 3.327s

57 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Jan@JLKM1 MINGW64 /f/mockups/gundb/griffinnode
$ node index.js
Hello wonderful person! :) Thanks for using GUN, please ask for help on http://c
hat.gun.eco if anything takes you longer than 5min to figure out!

Jan@JLKM1 MINGW64 /f/mockups/gundb/griffinnode
$

```

How do I get up and running with this repo. Just a minimum of instruction would come in handy.

**Comment by giraffekey** [comment]
What is in index.js?

**Comment by JLKM** [comment]
It's this one, which I've moved in order to get something to work with: https://github.com/GiraffeKey/griffin/blob/main/node/index.js

This approach is likely to be far fetched. But please tell, how it's done properly.

**Comment by giraffekey** [comment]
I use a hidden `test.js` for testing the code

```js
const Griffin = require("./node")

async function main() {
	const griffin = await Griffin()
	await griffin.create("username", "password")
	await griffin.auth("username", "password")

	const db = griffin.namespace("my-app")

	const col = await db.collection("my-collection")
	// do some operations and print their results
}
main()
```

**Comment by JLKM** [comment]
Still not there, yet, I'm affraid:

```
$ node test.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './node'
Require stack:
- F:\mockups\gundb\griffinnode\test.js
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880
:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:952:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:88:18)?[39m
    at Object.<anonymous> (F:\mockups\gundb\griffinnode\test.js:1:17)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:1
0)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:928:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:72:12)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [ ?[32m'F:\\mockups\\gundb\\griffinnode\\test.js'?[39m ]
}
```

File structure:

![billede](https://user-images.githubusercontent.com/18215374/106200185-e6db3580-61b6-11eb-9271-5687fa7d3efc.png)

**Comment by giraffekey** [comment]
In your case it would be `require(".")` since you put index.js in the root. For my setup it's `node/index.js`, `core/index.js`, `browser/index.js`.

**Comment by JLKM** [comment]
Now, we're talking...

```
Jan@JLKM1 MINGW64 /f/mockups/gundb/griffinnode
$ node test.js
Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes
you longer than 5min to figure out!
AXE enabled.
Multicast on 233.255.255.255:8765
Listening on: /ip4/192.168.1.56/tcp/54045/p2p/QmdwNAUTMKo1rjWbu24av9hP6UdHk7bnh429zprGNf9VR9
Listening on: /ip4/169.254.144.205/tcp/54045/p2p/QmdwNAUTMKo1rjWbu24av9hP6UdHk7bnh429zprGNf9VR9
Listening on: /ip4/192.168.1.46/tcp/54045/p2p/QmdwNAUTMKo1rjWbu24av9hP6UdHk7bnh429zprGNf9VR9
Listening on: /ip4/127.0.0.1/tcp/54045/p2p/QmdwNAUTMKo1rjWbu24av9hP6UdHk7bnh429zprGNf9VR9

```

But nothing to se on 233.255.255.255:8765

**Comment by giraffekey** [comment]
There is a lot of extra stuff I added. The library is in an experimental state.

The multicast is just something AXE logs, I'm not actually sure what it does as that's an experimental part of GUN.

My `test.js` file only tests the MongoDB-like query language. The backup over DHT mechanism hasn't been tested at all yet which is what the libp2p stuff is all about.

What are you using the repo for exactly?

**Comment by JLKM** [comment]
Hoped to get at least a basis for running a CMS on GunDB...

**Comment by giraffekey** [comment]
Ah, I recently published a notice in the README that goes over how this library is mostly for my own personal biased use cases at the moment and not ready for public use.

I am currently building a production application with Griffin to experiment with real world use cases. Expect the API to be unstable as I am going to shape what Griffin becomes around what the application needs.

You are free to use Griffin for whatever you wish, however since I am so wrapped up in my own cases I won't be able to help you with yours. If you need anything you'll likely have to implement it yourself. I can offer advice and direction for any issues you open but not labor.

**Comment by JLKM** [comment]
That's just fine. I apparently got this wrong. Will take another road. Thanks for enlightning me about this so quick. Good luck with your project.

**Comment by giraffekey** [comment]
Lemme know how your project goes, I'd be interested in knowing how GUN gets used and what your requirements are.

Also if you ever come back to Griffin feel free to open an issue for functionality you'd like to see.
